#!/usr/bin/env python3

"""
This example demonstrates how to use SIMSOPT to compute Poincare plots.

This example also illustrates how the coil shapes resulting from a
simsopt stage-2 optimization can be loaded in to another script for
analysis.  The coil shape data used in this script,
``inputs/biot_savart_opt.json``, can be re-generated by running the
example 2_Intermediate/stage_two_optimization.py.

This example takes advantage of MPI if you launch it with multiple
processes (e.g. by mpirun -n or srun), but it also works on a single
process.
"""

import logging
import os
import sys
import time

import matplotlib.pyplot as plt
import numpy as np
import simsopt
import simsoptpp as sopp
from simsopt._core.util import parallel_loop_bounds
from simsopt.field import (  # particles_to_vtk,
    InterpolatedField,
    LevelsetStoppingCriterion,
    MaxRStoppingCriterion,
    MaxZStoppingCriterion,
    MinRStoppingCriterion,
    MinZStoppingCriterion,
    SurfaceClassifier,
    compute_fieldlines,  # plot_poincare_data,
)
from simsopt.geo import RotatedCurve, SurfaceBSpline, SurfaceRZFourier
from simsopt.util import comm_world, proc0_print

sys.path.insert(
    0, os.path.join(os.path.dirname(__file__), "..", "..", "corner_sharpening")
)
from sharpen_fixed_s_twin import (  # noqa: E402
    build_sharpened_twins,
    compute_uphi_grid_interpolated,
    mirror_position_to_phi,
    plot_leg_length_grid,
    reduce_phi_to_fundamental_domain,
)

proc0_print("Running 1_Simple/tracing_fieldlines_QA.py")
proc0_print("=========================================")

logging.basicConfig()
logger = logging.getLogger("simsopt.field.tracing")
logger.setLevel(1)

# coils_filename = "20240303-02-stage_2_filament_optimization_for_x_point/theta0_1.0_ncoils_4_order_6_R1_0.73_length_target_3.5_weight_0.11_max_curvature_5.8_weight_0.00073_msc_9.9_weight_1.2e-06/biot_savart1.json"
# coils_filename = "20240303-02-stage_2_filament_optimization_for_x_point/theta0_1.0_ncoils_4_order_12_R1_0.88_length_target_4.3_weight_1.3_max_curvature_9.9_weight_9.2e-05_msc_5.0_weight_2.8e-07/biot_savart1.json"
# coils_filename = "20240304-01-stage_2_filament_optimization_for_x_point/theta0_0.6_ncoils_4_order_14_R1_0.49_length_target_4.3_weight_0.3_max_curvature_9.5_weight_6.1e-07_msc_1.1e+01_weight_5e-05/biot_savart1.json"
# coils_filename = "20240304-01-stage_2_filament_optimization_for_x_point/theta0_0.6_ncoils_4_order_13_R1_0.54_length_target_4.1_weight_3.8_max_curvature_9.2_weight_4.1e-07_msc_8.7_weight_4.5e-07/biot_savart1.json"
# coils_filename = "20240304-01-stage_2_filament_optimization_for_x_point/theta0_0.84_ncoils_4_order_16_R1_0.8_length_target_4.4_weight_0.1_max_curvature_1.4e+01_weight_1.7e-05_msc_5.1_weight_2.5e-06/biot_savart1.json"
# coils_filename = "20240304-01-stage_2_filament_optimization_for_x_point/theta0_0.84_ncoils_4_order_10_R1_0.71_length_target_4.0_weight_0.11_max_curvature_1.4e+01_weight_2.6e-05_msc_7.5_weight_1.2e-07/biot_savart1.json"
# coils_filename = "20240304-01-stage_2_filament_optimization_for_x_point/theta0_0.88_ncoils_4_order_10_R1_0.54_length_target_3.8_weight_4.6_max_curvature_7.6_weight_1.1e-06_msc_1.4e+01_weight_4.8e-07/biot_savart1.json"
# coils_filename = "/Users/issraali/codes/simsopt/figures_spline_paper/x_point/da_remix/stage_2_scan_twin_out/order_10_R1_0.42_length_target_4.8_weight_0.21_max_curvature_7.1_weight_0.00022_msc_1.4e+01_weight_0.00044_cc_0.11_weight_9.7e+01/biot_savart.json"
# manifold-optimization refinement of the above (see manifold_opt_twin.py):
coils_filename = "/Users/issraali/codes/simsopt/figures_spline_paper/x_point/da_remix/stage_2_scan_twin_out/order_10_R1_0.42_length_target_4.8_weight_0.21_max_curvature_7.1_weight_0.00022_msc_1.4e+01_weight_0.00044_cc_0.11_weight_9.7e+01/manifold_opt/biot_savart.json"

# If we're in the CI, make the run a bit cheaper:
# nfieldlines = 3 if in_github_actions else 10
# tmax_fl = 10000 if in_github_actions else 20000
# nfieldlines = 10
tmax_fl = 10000
# tmax_fl = 1
tol = 1e-13
degree = 4  # 2 if in_github_actions else 4

interpolant_n = 20
# Box must contain surf1_Poincare (R in [0.74, 1.17], Z in [-0.52, 0.52] for
# the theta0_0.88 X-point equilibrium) plus the surf_classifier envelope
# (R00 +/- b, Z +/- b below) with margin.
Zmax = 0.75
Rmax = 1.7
Rmin = 0.2

# nfieldlines = 20
# R0 = np.ones(nfieldlines)
# Z0 = np.linspace(0, 0.3, nfieldlines)

n_core_fieldlines = 8
# R0_core/Z0_core (a vertical chord of seed points from the magnetic
# axis outward) are computed below, once spline_surf's own geometry is
# available -- R=1.0 was just the coils' own winding-surface major
# radius, not necessarily anywhere near this particular (sharpened
# QUASR) equilibrium's actual axis, so hardcoding R0_core=1 could seed
# core field lines outside the real confined region entirely.

delta_initial_conditions = 0.01
inital_conditions_ntheta = 20
inital_conditions_nphi = 25
nfieldlines = (
    n_core_fieldlines + inital_conditions_ntheta * inital_conditions_nphi * 2
)

# R01d = np.linspace(1, 1.02, 3)
# Z01d = np.linspace(0.2, 0.26, 10)
# R02d, Z02d = np.meshgrid(R01d, Z01d)
# R0 = np.concatenate((R02d.flatten(), np.ones(n_core_fieldlines)))
# Z0 = np.concatenate((Z02d.flatten(), np.linspace(0, 0.22, n_core_fieldlines)))
# nfieldlines = R0.size

bottom_str = (
    os.path.abspath(__file__)
    + f"  tol:{tol}  interpolant_n:{interpolant_n}  tmax:{tmax_fl}  nfieldlines: {nfieldlines} degree:{degree}"
)

# Directory for output
OUT_DIR = "./"
# os.makedirs(OUT_DIR, exist_ok=True)

# Load in the boundary surface:
# filename = TEST_DIR / 'input.LandremanPaul2021_QA'
## Note that the range must be "full torus"!
# surf = SurfaceRZFourier.from_vmec_input(filename, nphi=200, ntheta=30, range="full torus")
# nfp = surf.nfp

nfp = 2

phi_range = "half period"

# Parameters of the target surface:
spline_kwargs = {
    "axis_points": 3,
    "points_per_cs": 48,
    "n_cs": 6,
    "nfp": 2,
    "M": 12,
    "N": 12,
    "p_u": 3,
    "p_v": 3,
    "cs_equispaced": True,
    "rays_equispaced": False,
    "cs_global_angle_free": False,
    "axis_angles_fixed": True,
    "cs_basis": "polar",
    "nurbs": False,
    "use_bishop_frame": True,
    "knot_parametrization": "uniform",
}


dofs = [
    0.14035348,
    0.13943751,
    0.13725011,
    0.13475654,
    0.13330573,
    0.13452571,
    0.14003699,
    0.15102683,
    0.1679519,
    0.19059529,
    0.21671552,
    0.24393745,
    0.27001378,
    0.3032171,
    0.33222144,
    0.35592851,
    0.3716055,
    0.34467597,
    0.3161583,
    0.28209825,
    0.2539144,
    0.22619991,
    0.20058927,
    0.18175057,
    0.17459356,
    0.0,
    0.13411203,
    0.27657128,
    0.43418522,
    0.61090804,
    0.80530498,
    1.00850143,
    1.20596105,
    1.38365066,
    1.53354284,
    1.65336663,
    1.74791506,
    1.82540285,
    1.90372987,
    1.95707362,
    1.99330356,
    2.01441219,
    2.06207428,
    2.1236243,
    2.21909965,
    2.32539351,
    2.45652478,
    2.63400145,
    2.86646341,
    3.14159265,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.11556551,
    0.12634513,
    0.1373894,
    0.14794901,
    0.15761603,
    0.16628398,
    0.1741545,
    0.18178037,
    0.19012268,
    0.20058107,
    0.21404161,
    0.23033642,
    0.24838441,
    0.26651105,
    0.28864193,
    0.31151089,
    0.33217702,
    0.34199909,
    0.3086764,
    0.28230488,
    0.25241582,
    0.22789764,
    0.20102497,
    0.17654925,
    0.16061555,
    0.16059377,
    0.17859515,
    0.20960933,
    0.24654206,
    0.28361466,
    0.32475907,
    0.36735282,
    0.39780426,
    0.41406249,
    0.38687778,
    0.35514701,
    0.31466853,
    0.27556029,
    0.24212717,
    0.20815389,
    0.17612119,
    0.14865918,
    0.12633228,
    0.10989787,
    0.10004871,
    0.09687202,
    0.09945876,
    0.1062166,
    6.25368054,
    0.11115297,
    0.23050683,
    0.33750191,
    0.43970786,
    0.54337289,
    0.65368223,
    0.77478286,
    0.90938482,
    1.05792502,
    1.20779781,
    1.34886403,
    1.47524234,
    1.5851509,
    1.70006746,
    1.78654511,
    1.84930333,
    1.87536257,
    1.94233389,
    2.00964797,
    2.10961802,
    2.21581682,
    2.3623655,
    2.57021229,
    2.85540602,
    3.1948015,
    3.50850403,
    3.74613552,
    3.91173645,
    4.02666085,
    4.12641195,
    4.20119538,
    4.24340795,
    4.26308837,
    4.2829491,
    4.31017221,
    4.35338276,
    4.40866607,
    4.46391187,
    4.53576096,
    4.63150553,
    4.75787915,
    4.9228504,
    5.13091039,
    5.37530251,
    5.63310339,
    5.87497455,
    6.08264807,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.09573116,
    0.11075934,
    0.12832219,
    0.14700564,
    0.16589972,
    0.18445357,
    0.20239562,
    0.21971286,
    0.23666849,
    0.25383961,
    0.27109698,
    0.28771528,
    0.30238115,
    0.32136351,
    0.34130576,
    0.36207648,
    0.33127027,
    0.29556717,
    0.25962615,
    0.22492566,
    0.18858368,
    0.1568896,
    0.13939102,
    0.14469147,
    0.1709069,
    0.20847966,
    0.24971827,
    0.29008559,
    0.32676969,
    0.36983345,
    0.41184036,
    0.44252269,
    0.46331813,
    0.44353731,
    0.41398993,
    0.37394589,
    0.32627329,
    0.2927623,
    0.25712797,
    0.22134117,
    0.18744534,
    0.15755159,
    0.13170383,
    0.11022651,
    0.09385241,
    0.08371343,
    0.08084239,
    0.08524989,
    0.02802324,
    0.214344,
    0.35696735,
    0.47074003,
    0.56773861,
    0.65658651,
    0.74337677,
    0.83252741,
    0.92728536,
    1.02990364,
    1.13326668,
    1.23286709,
    1.33145046,
    1.43264707,
    1.51467838,
    1.58361166,
    1.63846018,
    1.71996012,
    1.83704259,
    1.96877826,
    2.15607485,
    2.43471823,
    2.82565867,
    3.25718806,
    3.60392913,
    3.83624024,
    3.98920919,
    4.09415758,
    4.16987633,
    4.24535556,
    4.30088881,
    4.33405794,
    4.35380609,
    4.3634662,
    4.37966307,
    4.40583553,
    4.44664674,
    4.47990327,
    4.52073458,
    4.57291725,
    4.64121191,
    4.73041693,
    4.84889327,
    5.00786103,
    5.21907837,
    5.48525551,
    5.78422647,
    6.07117123,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.08653231,
    0.10807275,
    0.13355873,
    0.16135072,
    0.19021283,
    0.21916578,
    0.24739439,
    0.27420449,
    0.29901097,
    0.3213468,
    0.34152275,
    0.36787337,
    0.39354671,
    0.43069714,
    0.41590586,
    0.38448671,
    0.34702003,
    0.31025421,
    0.27295069,
    0.23056948,
    0.18714582,
    0.14956142,
    0.12961216,
    0.13827778,
    0.1711373,
    0.21544189,
    0.2630552,
    0.30936676,
    0.35140535,
    0.39570261,
    0.44575061,
    0.48173632,
    0.50431961,
    0.48030163,
    0.44238875,
    0.390182,
    0.33944043,
    0.29856694,
    0.25577175,
    0.21355893,
    0.17451516,
    0.14135414,
    0.11355713,
    0.09095749,
    0.07402552,
    0.06414237,
    0.06305005,
    0.07102319,
    0.31365838,
    0.51343602,
    0.65627371,
    0.76220917,
    0.84548587,
    0.91524057,
    0.97738789,
    1.03597505,
    1.09400985,
    1.15396086,
    1.22001708,
    1.29366637,
    1.35222337,
    1.42094497,
    1.44027588,
    1.48716095,
    1.55671113,
    1.64854916,
    1.74411306,
    1.87481598,
    2.06892779,
    2.37482651,
    2.82971585,
    3.33002694,
    3.70617488,
    3.94826366,
    4.10663533,
    4.21647442,
    4.29689585,
    4.37250324,
    4.43712649,
    4.47430939,
    4.49466108,
    4.50085833,
    4.51202306,
    4.53098917,
    4.55542078,
    4.57581532,
    4.60118246,
    4.63566949,
    4.6854597,
    4.75854863,
    4.86633626,
    5.02632603,
    5.26195586,
    5.58804796,
    5.97021668,
    0.04024789,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.05100848,
    0.08120092,
    0.11924665,
    0.15955777,
    0.20004971,
    0.23947947,
    0.276874,
    0.31138351,
    0.34224328,
    0.37278368,
    0.41340164,
    0.4489029,
    0.47974653,
    0.50009281,
    0.4613023,
    0.42348385,
    0.37552938,
    0.33963993,
    0.29747576,
    0.25012376,
    0.20133215,
    0.1573531,
    0.12965599,
    0.13188652,
    0.16227796,
    0.2064544,
    0.25525708,
    0.30382578,
    0.34924267,
    0.38936956,
    0.43739708,
    0.48398287,
    0.51585041,
    0.53305193,
    0.50970504,
    0.47726765,
    0.43323843,
    0.38101718,
    0.34648418,
    0.30964123,
    0.27219828,
    0.23588498,
    0.20041622,
    0.16556065,
    0.13121626,
    0.09764769,
    0.06642713,
    0.04482662,
    0.33032382,
    0.76533623,
    0.94855987,
    1.04281485,
    1.10137903,
    1.14398928,
    1.17947574,
    1.21251843,
    1.24605559,
    1.28959333,
    1.33815342,
    1.37275159,
    1.39834115,
    1.41337879,
    1.45458297,
    1.5031862,
    1.58191239,
    1.65499339,
    1.74124327,
    1.86030986,
    2.03769767,
    2.32139126,
    2.76838816,
    3.30848902,
    3.73525258,
    4.01036039,
    4.18952852,
    4.31378153,
    4.40495769,
    4.47457909,
    4.54915285,
    4.60421258,
    4.6354414,
    4.6505781,
    4.65440832,
    4.66035446,
    4.669857,
    4.68457751,
    4.69431154,
    4.70467037,
    4.71722564,
    4.73421663,
    4.75859768,
    4.79581679,
    4.85705518,
    4.96885725,
    5.20659862,
    5.78067986,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.04400226,
    0.06778231,
    0.11143659,
    0.15824601,
    0.20465185,
    0.24929407,
    0.29130066,
    0.32995472,
    0.36460817,
    0.40302679,
    0.44995086,
    0.48787893,
    0.5169624,
    0.53926695,
    0.5163347,
    0.48568395,
    0.44277194,
    0.39305977,
    0.35608533,
    0.31321839,
    0.26651191,
    0.2186048,
    0.17351766,
    0.13837926,
    0.12444496,
    0.0,
    0.84508947,
    1.13149112,
    1.24467935,
    1.30198429,
    1.33670494,
    1.36130371,
    1.38152892,
    1.40052754,
    1.42618976,
    1.45161369,
    1.46851038,
    1.47975536,
    1.48754343,
    1.5068724,
    1.53587815,
    1.58415728,
    1.65734848,
    1.71833881,
    1.7975938,
    1.90455382,
    2.05657341,
    2.2859819,
    2.64327847,
    3.14159265,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.92175992,
    1.1061464,
    1.21557964,
    0.0,
    0.07962817,
    0.0,
    0.0,
    0.78539816,
    1.57079633,
    0.0,
    0.31415927,
    0.62831853,
    0.9424778,
    1.25663706,
    1.57079633,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
]

R00 = 0.95

# Resolution on each surface for the Bnormal objective:
nphi = 32
ntheta = 64

# Sharpen and split into the two crossover "twin" surfaces (see
# corner_sharpening/sharpen_fixed_s_twin.py's module docstring). These
# dofs already encode a sharp corner directly at their final
# points_per_cs=48 resolution (verified: re-sharpening barely moves
# anything -- both corner-finding criteria agree to ~0.01 rad and the
# two corners are always well-separated), so refine_poloidal_count=0
# (spline_kwargs already describes that final resolution, not a
# pre-refine_poloidal one). Same parameter values as stage_2_scan_twin.py.
D_CRAWL = 0.05
D_EXT = 0.18
CORNER_CRITERION = "z"
N_PHI = 30
NTHETA = 20
LEG_FRACTION = 0.02


def build_surfaces():
    """The twin crossover surfaces this equilibrium's X-point boundary
    splits into (see build_sharpened_twins) -- same construction
    pattern as stage_2_scan_twin.py's build_flux_grids(), including
    showing both twins on their own custom (u, phi) grid before using
    them for anything else."""
    spline_surf = SurfaceBSpline(**spline_kwargs)
    spline_surf.unfix_all()
    spline_surf.x = dofs

    spline_surf, surf_outboard, surf_inboard, grids = build_sharpened_twins(
        spline_surf,
        spline_kwargs,
        D_CRAWL,
        D_EXT,
        LEG_FRACTION,
        CORNER_CRITERION,
        n_phi=N_PHI,
        ntheta=NTHETA,
        refine_poloidal_count=0,
    )

    fig, _ax = plot_leg_length_grid(
        spline_surf,
        grids["geometry"],
        surf_outboard,
        surf_inboard,
        grids["outboard_is_between"],
        LEG_FRACTION,
        grids["phis"],
        ntheta=NTHETA,
    )
    fig.savefig(OUT_DIR + "flux_grids.png")
    plt.show()

    return (
        spline_surf,
        surf_outboard,
        surf_inboard,
        grids["geometry"],
        grids["outboard_is_between"],
    )


spline_surf, surf_outboard, surf_inboard, geometry, outboard_is_between = (
    build_surfaces()
)


surf_classifier = SurfaceRZFourier.from_nphi_ntheta(
    mpol=1,
    ntor=1,
    nfp=nfp,
    nphi=nphi,
    ntheta=ntheta,
    range="full torus",
)

phi_range = "field period"
quadpoints_phi_ic, quadpoints_theta_ic = SurfaceBSpline.get_quadpoints(
    nphi=inital_conditions_nphi,
    ntheta=inital_conditions_ntheta,
    range=phi_range,
    nfp=nfp,
)
phi_ic, theta_ic = np.meshgrid(
    quadpoints_phi_ic, quadpoints_theta_ic, indexing="ij"
)
phi_ic_flat, theta_ic_flat = phi_ic.reshape(-1), theta_ic.reshape(-1)


def _sol_seed_points(surf, phi_flat, theta_flat, delta):
    """Points `delta` outward, past the LCFS into the SOL, along surf's
    own unit normal (which points inward, hence the minus sign) --
    replaces the old SurfaceHelicalArc `radius_a + delta` trick, which
    has no direct equivalent for SurfaceBSpline's dofs."""
    pos, g1, g2 = surf._gamma_and_derivs(phi_flat, theta_flat, max_deriv=1)
    normal = np.cross(g1, g2, axis=1)
    unitnormal = normal / np.linalg.norm(normal, axis=1, keepdims=True)
    return pos - delta * unitnormal


# Seed SOL field lines from BOTH twins -- each is one of the two
# surfaces the real X-point boundary splits into right at the corner.
initial_conditions_sol = np.vstack(
    [
        _sol_seed_points(
            surf_outboard, phi_ic_flat, theta_ic_flat, delta_initial_conditions
        ),
        _sol_seed_points(
            surf_inboard, phi_ic_flat, theta_ic_flat, delta_initial_conditions
        ),
    ]
)
# R0_core/Z0_core, from spline_surf's OWN geometry at phi=0: a chord of
# seed points along the OUTBOARD MIDPLANE (Z=0, R increasing from the
# axis toward the edge) -- the standard convention for a rho scan (rho
# = fraction of the minor radius from axis to edge), NOT a vertical
# line at fixed R (moving in Z at fixed R doesn't track a rho
# coordinate at all -- rho=0.9 here means R close to the OUTBOARD
# edge, near the coils' own R0=1.0, not a large Z excursion at the
# axis's own R). Rather than the hardcoded R=1.0 guess (just the
# coils' winding-surface major radius, with no reason to sit near this
# equilibrium's actual magnetic axis), R_axis_guess/minor_radius come
# from the boundary's own R extent at phi=0.
cross_section_phi0 = spline_surf.cross_section(phi=0.0, thetas=400)
R_cs0 = np.hypot(cross_section_phi0[:, 0], cross_section_phi0[:, 1])
Z_cs0 = cross_section_phi0[:, 2]
R_axis_guess = 0.5 * (R_cs0.max() + R_cs0.min())
minor_radius = 0.5 * (R_cs0.max() - R_cs0.min())
RHO_MAX_CORE = 0.9  # spread seeds out to this fraction of minor_radius
rho_core = np.linspace(0, RHO_MAX_CORE, n_core_fieldlines)
R0_core = R_axis_guess + rho_core * minor_radius
Z0_core = np.zeros(n_core_fieldlines)
proc0_print(
    f"Core field line seeds: R_axis={R_axis_guess:.4f} (minor_radius={minor_radius:.4f}), "
    f"R in [{R0_core[0]:.4f}, {R0_core[-1]:.4f}] at Z=0 (rho_max={RHO_MAX_CORE})"
)

initial_conditions_core = np.array(
    [R0_core, np.zeros(n_core_fieldlines), Z0_core]
).T
initial_conditions = np.vstack(
    (initial_conditions_sol, initial_conditions_core)
)

# classifier_aminor = 0.22
# classifier_elongation = 3.2
# Sphere of radius classifier_aminor centered at R00: measured via
# SurfaceClassifier.evaluate_xyz against surf1_Poincare, this gives a
# ~0.08 minimum clearance to the target surface everywhere (0.5 gave -0.016,
# i.e. the target poked outside).
classifier_aminor = 0.6
classifier_elongation = 1
classifier_elongation_inv = 1 / classifier_elongation
b = classifier_aminor / np.sqrt(classifier_elongation_inv)
surf_classifier.set_rc(0, 0, R00)
surf_classifier.set_rc(1, 0, 0.5 * b * (classifier_elongation_inv + 1))
surf_classifier.set_zs(1, 0, 0.5 * b * (classifier_elongation_inv + 1))
surf_classifier.set_rc(1, 1, 0.5 * b * (classifier_elongation_inv - 1))
surf_classifier.set_zs(1, 1, -0.5 * b * (classifier_elongation_inv - 1))
surf_classifier.x = surf_classifier.x

# Load in the optimized coils from stage_two_optimization.py:
# coils_filename = Path(__file__).parent / "inputs" / "biot_savart_opt.json"
bs = simsopt.load(coils_filename)
# simsopt.load restores whatever points were last set on `bs` before it
# was saved -- for a BiotSavart saved by stage_2_scan_twin.py, that's
# the restricted (600-point) crossover-leg grid near ONE twin's own
# corners (see SquaredFluxOnGrid), not a representative sample of the
# whole boundary. ml_originals' script instead set points to the
# FULL closed surface (bs1.set_points(surf1.gamma()...)) before saving,
# so its <B> scaling factor was a genuine device-average. Match that
# intent here by re-setting points to both twins' full closed loops
# before computing the factor -- otherwise the "average" is skewed by
# whatever locally-stronger/weaker field happens to sit right at the
# X-point, not representative of the device as a whole.
bs.set_points(
    np.concatenate(
        [surf_outboard.gamma().reshape((-1, 3)), surf_inboard.gamma().reshape((-1, 3))]
    )
)
proc0_print("Currents before scaling:", [c.current.full_x[0] for c in bs.coils])
factor = np.mean(bs.AbsB())
proc0_print("<B> before scaling:", factor)
for c in bs.coils:
    if not isinstance(c.curve, RotatedCurve):
        c.current.full_x = c.current.full_x / factor
proc0_print("Currents after scaling:", [c.current.full_x[0] for c in bs.coils])
proc0_print("<B> after scaling:", np.mean(bs.AbsB()))

# surf.to_vtk(OUT_DIR + 'surface')
sc_fieldline = SurfaceClassifier(surf_classifier, h=0.02, p=2)  # , buffer=0.01)
sc_fieldline.to_vtk(OUT_DIR + "levelset", h=0.02)


# stopping_criteria=[
#     MaxZStoppingCriterion(0.27),
#     MinZStoppingCriterion(-0.27),
#     MaxRStoppingCriterion(1.27),
#     MinRStoppingCriterion(0.73),
# ]
stopping_criteria = [
    MaxZStoppingCriterion(Zmax),
    MinZStoppingCriterion(-Zmax),
    MaxRStoppingCriterion(Rmax),
    MinRStoppingCriterion(Rmin),
    LevelsetStoppingCriterion(sc_fieldline.dist),
]
# stopping_criteria = []
# stopping_criteria=[
#     MaxZStoppingCriterion(0.27),
#     MinZStoppingCriterion(-0.27),
# ]
# stopping_criteria=[
#     #MaxRStoppingCriterion(1.5),
#     MinRStoppingCriterion(0.2),
# ]


# Same as simsopt's compute_fieldlines, but also accept an input phi0 array.
def compute_fieldlines(
    field,
    xyz_inits,
    tmax=10000,
    tol=1e-7,
    phis=[],
    stopping_criteria=[],
    comm=None,
):
    r"""
    Compute magnetic field lines by solving

    .. math::

        [\dot x, \dot y, \dot z] = B(x, y, z)

    Args:
        field: the magnetic field :math:`B`
        R0: list of radial components of initial points
        Z0: list of vertical components of initial points
        tmax: for how long to trace. will do roughly ``|B|*tmax/(2*pi*r0)`` revolutions of the device
        tol: tolerance for the adaptive ode solver
        phis: list of angles in [0, 2pi] for which intersection with the plane
              corresponding to that phi should be computed
        stopping_criteria: list of stopping criteria, mostly used in
                           combination with the ``LevelsetStoppingCriterion``
                           accessed via :obj:`simsopt.field.tracing.SurfaceClassifier`.

    Returns: 2 element tuple containing
        - ``res_tys``:
            A list of numpy arrays (one for each particle) describing the
            solution over time. The numpy array is of shape (ntimesteps, 4).
            Each row contains the time and
            the position, i.e.`[t, x, y, z]`.
        - ``res_phi_hits``:
            A list of numpy arrays (one for each particle) containing
            information on each time the particle hits one of the phi planes or
            one of the stopping criteria. Each row of the array contains
            `[time, idx, x, y, z]`, where `idx` tells us which of the `phis`
            or `stopping_criteria` was hit.  If `idx>=0`, then `phis[int(idx)]`
            was hit. If `idx<0`, then `stopping_criteria[int(-idx)-1]` was hit.
    """
    nlines = xyz_inits.shape[0]
    # assert len(R0) == len(Z0)
    # assert len(R0) == len(phi0)
    # nlines = len(R0)
    # xyz_inits = np.zeros((nlines, 3))
    # R0 = np.asarray(R0)
    # phi0 = np.asarray(phi0)
    # xyz_inits[:, 0] = R0 * np.cos(phi0)
    # xyz_inits[:, 1] = R0 * np.sin(phi0)
    # xyz_inits[:, 2] = np.asarray(Z0)
    res_tys = []
    res_phi_hits = []
    first, last = parallel_loop_bounds(comm, nlines)
    for i in range(first, last):
        res_ty, res_phi_hit = sopp.fieldline_tracing(
            field,
            xyz_inits[i, :],
            tmax,
            tol,
            phis=phis,
            stopping_criteria=stopping_criteria,
        )
        res_tys.append(np.asarray(res_ty))
        res_phi_hits.append(np.asarray(res_phi_hit))
        dtavg = res_ty[-1][0] / len(res_ty)
        logger.debug(
            f"{i + 1:3d}/{nlines}, t_final={res_ty[-1][0]}, average timestep {dtavg:.10f}s"
        )
    if comm is not None and comm.Get_size() > 1:
        # Skip the no-op gather on a single rank: with tmax_fl this large,
        # most trajectories never hit a stopping criterion, so res_tys is
        # huge, and mpi4py's pickle-based allgather chokes on the buffer
        # size even when there's nothing to gather (MPI_ERR_ARG).
        res_tys = [i for o in comm.allgather(res_tys) for i in o]
        res_phi_hits = [i for o in comm.allgather(res_phi_hits) for i in o]
    return res_tys, res_phi_hits


def particles_to_vtk(res_tys, filename):
    """
    Export particle tracing or field lines to a vtk file.
    Expects that the xyz positions can be obtained by ``xyz[:, 1:4]``.
    """
    from pyevtk.hl import polyLinesToVTK

    # res_tys0 = res_tys.copy()
    res_tys_stellsym = []
    for xyz in res_tys:
        xyz_flipped = xyz.copy()
        # Flip y and z, not x
        xyz_flipped[:, 2] = -xyz[:, 2]
        xyz_flipped[:, 3] = -xyz[:, 3]
        res_tys_stellsym.append(xyz_flipped)

    res_tys0 = res_tys + res_tys_stellsym

    res_tys = []
    for xyz in res_tys0:
        # xyz = res_tys0[j]
        for i in range(nfp):
            # phi = np.atan2(xyz[:, 2], xyz[:, 1])
            xyz_new = np.zeros_like(xyz)
            angle = i * 2 * np.pi / nfp
            xyz_new[:, 0] = xyz[:, 0]
            xyz_new[:, 1] = xyz[:, 1] * np.cos(angle) + xyz[:, 2] * np.sin(
                angle
            )
            xyz_new[:, 2] = xyz[:, 1] * -(np.sin(angle)) + xyz[:, 2] * np.cos(
                angle
            )
            xyz_new[:, 3] = xyz[:, 3]
            res_tys.append(xyz_new)

    t = np.concatenate([xyz[:, 0] for xyz in res_tys])
    x = np.concatenate([xyz[:, 1] for xyz in res_tys])
    y = np.concatenate([xyz[:, 2] for xyz in res_tys])
    z = np.concatenate([xyz[:, 3] for xyz in res_tys])
    ppl = np.asarray([xyz.shape[0] for xyz in res_tys])
    data = np.concatenate(
        [i * np.ones((res_tys[i].shape[0],)) for i in range(len(res_tys))]
    )
    rand = np.concatenate(
        [
            np.random.rand() * np.ones((res_tys[i].shape[0],))
            for i in range(len(res_tys))
        ]
    )
    pointData = {"idx": data, "time": t, "rand": rand}
    polyLinesToVTK(filename, x, y, z, pointsPerLine=ppl, pointData=pointData)


def plot_poincare_data(
    fieldlines_phi_hits,
    phis,
    filename,
    mark_lost=False,
    aspect="equal",
    dpi=300,
    xlims=None,
    ylims=None,
    s=2,
    marker="o",
):
    """
    Create a poincare plot. Usage:

    .. code-block::

        phis = np.linspace(0, 2*np.pi/nfp, nphis, endpoint=False)
        res_tys, res_phi_hits = compute_fieldlines(
            bsh, R0, Z0, tmax=1000, phis=phis, stopping_criteria=[])
        plot_poincare_data(res_phi_hits, phis, '/tmp/fieldlines.png')

    Requires matplotlib to be installed.

    """
    plt.rc("font", size=7)
    # nrowcol = ceil(sqrt(len(phis)))
    nrowcol = 2
    plt.figure()
    fig, axs = plt.subplots(nrowcol, nrowcol, figsize=(8, 5))
    for ax in axs.ravel():
        ax.set_aspect(aspect)
    color = None
    prop_cycle = plt.rcParams["axes.prop_cycle"]
    colors = prop_cycle.by_key()["color"]
    # for i in range(len(phis)):
    for i in range(4):
        row = i // nrowcol
        col = i % nrowcol

        # Plot only the crossover-leg u values each twin actually
        # contributed to the coil optimization's flux grid (see
        # compute_uphi_grid_interpolated in stage_2_scan_twin.py) --
        # NOT the full closed-loop boundary, most of which the flux
        # objective never touched. `phis[i]` is in RADIANS
        # (compute_fieldlines' own convention), but
        # compute_uphi_grid_interpolated's phis are normalized [0, 1)
        # fractions -- dividing here is required, not optional (only
        # phi=0 would happen to line up otherwise).
        #
        # compute_uphi_grid_interpolated only accepts phi within
        # spline_surf's own fundamental domain (one field-period half,
        # e.g. [0, 0.25] here) -- Poincare sections span a full field
        # period, so phis[i]/(2*pi) can exceed that (e.g. 0.375 at
        # phi=0.75*pi). Passing it straight through would silently
        # clamp to the wrong, non-mirrored geometry (verified: this
        # was the cause of the boundary outline not matching the 3D
        # flux_grids.png plot, which never leaves the fundamental
        # domain). reduce_phi_to_fundamental_domain +
        # mirror_position_to_phi correctly wrap/mirror instead.
        phi_frac_true = phis[i] / (2 * np.pi)
        phi_frac, mirrored = reduce_phi_to_fundamental_domain(
            spline_surf, phi_frac_true
        )
        for surf, keep_between, color in (
            (surf_outboard, outboard_is_between, "tab:red"),
            (surf_inboard, not outboard_is_between, "tab:blue"),
        ):
            grid = compute_uphi_grid_interpolated(
                spline_surf,
                geometry,
                LEG_FRACTION,
                keep_between,
                [phi_frac],
                ntheta=NTHETA,
            )
            pos = np.zeros((NTHETA, 3))
            surf.gamma_lin(
                pos, grid["phi"].reshape(-1), grid["theta"].reshape(-1)
            )
            if mirrored:
                pos = mirror_position_to_phi(pos, phi_frac_true)
            r_interp = np.hypot(pos[:, 0], pos[:, 1])
            z_interp = pos[:, 2]
            axs[row, col].plot(r_interp, z_interp, linewidth=1, c=color)

        axs[row, col].grid(True, linewidth=0.5)

        # if i != len(phis) - 1:
        if i != 4 - 1:
            axs[row, col].set_title(
                f"$\\phi = {phis[i] / np.pi:.3f}\\pi$ ", loc="left", y=0.0
            )
        else:
            axs[row, col].set_title(
                f"$\\phi = {phis[i] / np.pi:.3f}\\pi$ ", loc="right", y=0.0
            )
        if row == nrowcol - 1:
            axs[row, col].set_xlabel("$R$")
        if col == 0:
            axs[row, col].set_ylabel("$Z$")
        if col == 1:
            axs[row, col].set_yticklabels([])
        if xlims is not None:
            axs[row, col].set_xlim(xlims)
        if ylims is not None:
            axs[row, col].set_ylim(ylims)
        for j in range(len(fieldlines_phi_hits)):
            if fieldlines_phi_hits[j].size == 0:
                continue
            if mark_lost:
                lost = fieldlines_phi_hits[j][-1, 1] < 0
                color = "r" if lost else "g"
            phi_hit_codes = fieldlines_phi_hits[j][:, 1]
            condition = np.logical_and(
                phi_hit_codes >= 0, np.mod(phi_hit_codes, 4) == i
            )
            indices = np.where(condition)[0]
            data_this_phi = fieldlines_phi_hits[j][indices, :]
            if data_this_phi.size == 0:
                continue
            r = np.sqrt(data_this_phi[:, 2] ** 2 + data_this_phi[:, 3] ** 2)
            color = colors[j % len(colors)]
            axs[row, col].scatter(
                r,
                data_this_phi[:, 4],
                marker=marker,
                s=s,
                linewidths=0,
                c=color,
            )

            # stellarator-symmetric points:
            new_row = row
            if i == 1 or i == 3:
                new_row = 1 - row

            axs[new_row, col].scatter(
                r,
                -data_this_phi[:, 4],
                marker=marker,
                s=s,
                linewidths=0,
                c=color,
            )

        # plt.rc('axes', axisbelow=True)

    plt.figtext(
        0.5,
        0.995,
        os.path.abspath(coils_filename),
        ha="center",
        va="top",
        fontsize=4,
    )
    plt.figtext(0.5, 0.005, bottom_str, ha="center", va="bottom", fontsize=6)
    plt.tight_layout()
    plt.savefig(filename, dpi=dpi)


def trace_fieldlines(bfield, label):
    t1 = time.time()
    # R0 = np.ones(nfieldlines) * 1.02
    # Z0 = np.linspace(0, 0.26, nfieldlines)
    # Z0 = np.linspace(0.15, 0.19, nfieldlines)
    # R0 = R02d.flatten()
    # Z0 = Z02d.flatten()
    # phis = [(i/4)*(2*np.pi/nfp) for i in range(4)]
    phis = [(i / 4) * (2 * np.pi / nfp) for i in range(4 * nfp)]
    fieldlines_tys, fieldlines_phi_hits = compute_fieldlines(
        bfield,
        initial_conditions,
        tmax=tmax_fl,
        tol=1e-10,
        comm=comm_world,
        phis=phis,
        stopping_criteria=stopping_criteria,
    )
    #    phis=phis, stopping_criteria=[LevelsetStoppingCriterion(sc_fieldline.dist)])
    t2 = time.time()
    proc0_print(
        f"Time for fieldline tracing={t2 - t1:.3f}s. Num steps={sum([len(l) for l in fieldlines_tys]) // nfieldlines}",
        flush=True,
    )
    if comm_world is None or comm_world.rank == 0:
        # particles_to_vtk(fieldlines_tys, __file__ + f"fieldlines_{label}")
        # radius = 0.3
        plot_poincare_data(
            fieldlines_phi_hits,
            phis,
            __file__ + f"_{label}.png",
            dpi=300,
            # xlims=[1 - radius, 1 + radius],
            # ylims=[-radius, radius],
            s=1,
            # surf=surf1_Poincare,
        )


# uncomment this to run tracing using the biot savart field (very slow!)
# trace_fieldlines(bs, 'bs')


rrange = (Rmin, Rmax, interpolant_n)
phirange = (0, 2 * np.pi / nfp, interpolant_n * 2)
# exploit stellarator symmetry and only consider positive z values:
zrange = (0, Zmax, interpolant_n // 2)


"""
# Bounds for the interpolated magnetic field chosen so that the surface is
# entirely contained in it
n = 20
rs = np.linalg.norm(surf.gamma()[:, :, 0:2], axis=2)
zs = surf.gamma()[:, :, 2]
rrange = (np.min(rs), np.max(rs), n)
phirange = (0, 2*np.pi/nfp, n*2)
# exploit stellarator symmetry and only consider positive z values:
zrange = (0, np.max(zs), n//2)


def skip(rs, phis, zs):
    # The RegularGrindInterpolant3D class allows us to specify a function that
    # is used in order to figure out which cells to be skipped.  Internally,
    # the class will evaluate this function on the nodes of the regular mesh,
    # and if *all* of the eight corners are outside the domain, then the cell
    # is skipped.  Since the surface may be curved in a way that for some
    # cells, all mesh nodes are outside the surface, but the surface still
    # intersects with a cell, we need to have a bit of buffer in the signed
    # distance (essentially blowing up the surface a bit), to avoid ignoring
    # cells that shouldn't be ignored
    rphiz = np.asarray([rs, phis, zs]).T.copy()
    dists = sc_fieldline.evaluate_rphiz(rphiz)
    skip = list((dists < -0.05).flatten())
    proc0_print("Skip", sum(skip), "cells out of", len(skip), flush=True)
    return skip
"""

proc0_print("Initializing InterpolatedField")
bsh = InterpolatedField(
    bs,
    degree,
    rrange,
    phirange,
    zrange,
    True,
    nfp=nfp,
    stellsym=True,  # skip=skip
)
proc0_print("Done initializing InterpolatedField.")

"""
bsh.set_points(surf.gamma().reshape((-1, 3)))
bs.set_points(surf.gamma().reshape((-1, 3)))
Bh = bsh.B()
B = bs.B()
proc0_print("Mean(|B|) on plasma surface =", np.mean(bs.AbsB()))

proc0_print("|B-Bh| on surface:", np.sort(np.abs(B-Bh).flatten()))
"""

proc0_print("Beginning field line tracing")
trace_fieldlines(bsh, "bsh")
# trace_fieldlines(bs, 'bs')

proc0_print("End of 1_Simple/tracing_fieldlines_QA.py")
proc0_print("========================================")
